### ISSUE TITLE
Missing text files in the data 

### ISSUE THREAD

**Issue by likhitha-dhanaraju** [sitzikbs/Nesti-Net#1]
The text files mentioned in the pcpnet_dataset are not there in the dataset downloaded.
Or if you could let us know what should be written in the text files, it would be really helpful.

**Comment by sitzikbs** [comment]
Do you mean `trainingset_temp.txt`  ? 
If so these are lists of model names that you want to train \ test on. 
You should have `trainingset_no_noise.txt`, `trainingset_whitenoise.txt`,  `trainingset_vardensity.txt`, and `trainingset_whitenoise_vardensity.txt` when downloading the dataset. Same for the validationset.

For debugging I recommend to create a smaller list of models (which I named `trainingset_temp.txt`, but you can name however you like) So you dont have to load all of the models.
