### ISSUE TITLE
Question about training and testing noise level

### ISSUE THREAD

**Issue by ziruiw-dev** [sitzikbs/Nesti-Net#3]
Hi @sitzikbs,

Thanks for releasing your code.

I am a little confused about what noise level do you use in training and testing. When you perform a training, did you train with all noise levels at once then test on different noise levels? or did you do (train on noise level A - test on noise level A) pairs? 

Best,
Ryan

**Comment by sitzikbs** [comment]
Hi @Ryan-Zirui-Wang ,
I used the same train-test split as in PCPNet. There is a .txt file containing the exact list of files for training and testing when you download the dataste. 
In my code, I put `trainingset_temp.txt` as a temporary file that contains much less models just so you can see that all is running well. 
If I am not mistaken, the original `trainingset_whitenoise.txt` file contains training examples with clean + 3 different noise levels (0.1, 0.05, 0.01) = total 32 files. Trainng is done on all of them together, not separate. 
The test is done separately on each of the noise levels. 
Best,
Itzik

**Comment by ziruiw-dev** [comment]
Hi @sitzikbs, many thanks for your reply. Best, Ryan
