### ISSUE TITLE
Orientation of normals

### ISSUE THREAD

**Issue by seva100** [sitzikbs/Nesti-Net#5]
Hi, big thanks for open sourcing this repository.

I encountered an issue related to the orientation of the predicted normals. As far as I understand, the prediction of the normal can be ambiguous, since it can be pointed either inside or outside the object. E.g., here is the prediction I obtained by Nesti-Net (using `test_n_est_w_experts.py` and the provided model weights):

<img src="https://user-images.githubusercontent.com/5861398/105993702-c082a080-60b7-11eb-83ac-cff43c543972.png" data-canonical-src="https://user-images.githubusercontent.com/5861398/105993702-c082a080-60b7-11eb-83ac-cff43c543972.png" width="241" height="216" />

while the ground truth normals look like this:

![gt](https://user-images.githubusercontent.com/5861398/105993732-c8dadb80-60b7-11eb-8a5e-51d0200e2059.png)

The green regions seem to be caused by the wrong orientation of the normals. If I invert them manually, the prediction becomes closer to the correct values there. I've also observed the same effect for other point clouds. 

Is it the expected behavior or I'm inferring the pipeline in the wrong way? If I'm running it correctly, is there any way to find which normals are facing in the wrong direction? I tried some simple heuristics but they only work for simple convex shapes.

**Comment by sitzikbs** [comment]
You are correct in your observation. Nesti-Net provides unoriented normals since it is local and has no inside-outside context (similar to other prominent methods like PCPNet and DeepFit). In the case of convex shapes you can simply check the sign of dot product between the point and the normal vector. For other, more complicated, shapes you can apply [CGAL MST](https://doc.cgal.org/latest/Point_set_processing_3/group__PkgPointSetProcessing3Algorithms.html#ga50c98d5c5ae5535bce6f32eddbd03f33).

**Comment by seva100** [comment]
Thank you! I will try CGAL MST.

**Comment by ivchgr01** [comment]
> Hi, big thanks for open sourcing this repository.
> 
> I encountered an issue related to the orientation of the predicted normals. As far as I understand, the prediction of the normal can be ambiguous, since it can be pointed either inside or outside the object. E.g., here is the prediction I obtained by Nesti-Net (using `test_n_est_w_experts.py` and the provided model weights):
> 
> <img alt="" width="241" height="216" src="https://user-images.githubusercontent.com/5861398/105993702-c082a080-60b7-11eb-83ac-cff43c543972.png">
> 
> while the ground truth normals look like this:
> 
> ![gt](https://user-images.githubusercontent.com/5861398/105993732-c8dadb80-60b7-11eb-8a5e-51d0200e2059.png)
> 
> The green regions seem to be caused by the wrong orientation of the normals. If I invert them manually, the prediction becomes closer to the correct values there. I've also observed the same effect for other point clouds.
> 
> Is it the expected behavior or I'm inferring the pipeline in the wrong way? If I'm running it correctly, is there any way to find which normals are facing in the wrong direction? I tried some simple heuristics but they only work for simple convex shapes.

Hi, would you mind telling me how you could visualize the normal of point cloud? Thanks!

**Comment by sitzikbs** [comment]
https://www.itzikbs.com/how-to-visualize-normal-vectors-on-3d-point-clouds

it is an old post but still works.

**Comment by seva100** [comment]
@ivchgr01 I've just used the [draw_geometries(...)](http://www.open3d.org/docs/release/tutorial/visualization/visualization.html#Function-draw_geometries) function from Open3D library for Python (after setting pointwise normals as their RGB colors).

**Comment by ivchgr01** [comment]
> @ivchgr01 I've just used the [draw_geometries(...)](http://www.open3d.org/docs/release/tutorial/visualization/visualization.html#Function-draw_geometries) function from Open3D library for Python (after setting pointwise normals as their RGB colors).

@seva100 Thanks! Would you mind sharing details how you setting pointwise normals as their RGB colors?

**Comment by seva100** [comment]
@ivchgr01 something like `point_cloud.colors = o3d.utility.Vector3dVector(normals * 0.5 + 0.5)`

**Comment by ivchgr01** [comment]
> @ivchgr01 something like `point_cloud.colors = o3d.utility.Vector3dVector(normals * 0.5 + 0.5)`

@seva100 Thank you so much!
