### ISSUE TITLE
Configuration for Python 3

### ISSUE THREAD

**Issue by seva100** [sitzikbs/Nesti-Net#6]
This is actually not an issue but a suggestion on how to change the code slightly to make it suitable for Python 3. Initially, I had trouble installing all the libraries (especially TensorFlow) for Python 2.7, as recommended in the readme, since it's no longer supported. 

For installation of Nesti-Net for Python 3 on Ubuntu 18.04.3 LTS with CUDA 10.0, I came up with the following conda environment:
* python 3.6.12
* tensorflow-gpu 1.14.0 (installed via `pip install tensorflow-gpu==1.14`)
* opencv 3.4.2 
* torch 1.3.0, torchvision 0.4.1
* cudatoolkit 10.0.130
* cudnn 7.6.5

I suspect that more actual versions of tensorflow-gpu and torch could be installed (also depending on the CUDA version), though with these ones I can confirm that it works on my machine.

I also had to change 2 files for their Python 3 support: `test_n_est_w_experts.py` ([new version](https://gist.github.com/seva100/6f876e000c048a07d38aa7fb6a733d4e)) and `experts_n_est.py` ([new version](https://gist.github.com/seva100/88bb8c5cc69f973da7f2972b9d42505c)). Perhaps other files needed for training can be changed in a similar fashion, but changing these should be sufficient for the inference of Nesti-Net. Hopefully, these guidelines can be useful for the community.

**Comment by sitzikbs** [comment]
Due to lack of time and resources, I will not make the change in the code but your comment can be used as a reference for future developers.  Thanks.
