### ISSUE TITLE
Visualize the normal of point cloud

### ISSUE THREAD

**Issue by ivchgr01** [sitzikbs/Nesti-Net#7]
I am trying to a way to visualize the normal of point cloud. Anyone knows how to do it? Thanks!

**Comment by sitzikbs** [comment]
https://www.itzikbs.com/how-to-visualize-normal-vectors-on-3d-point-clouds

This is a blog post I wrote a while ago. It still works.

**Comment by ivchgr01** [comment]
> https://www.itzikbs.com/how-to-visualize-normal-vectors-on-3d-point-clouds
> 
> This is a blog post I wrote a while ago. It still works.

Thank you so much!
