### ISSUE TITLE
About the NYU depth V2 and ScanNet dataset

### ISSUE THREAD

**Issue by liuhw923** [sitzikbs/Nesti-Net#8]
How to pre-process these two datasets into .xyz format? 
thank you.

**Comment by sitzikbs** [comment]
It is slightly different for both but the principle is the same. See MATLAB dir, there is a designated function to convert ScanNet scans into points. then to export to .xyz is simply saving the points array.

**Comment by liuhw923** [comment]
Thank you for your reply!
